spring:
  application:
    name: user-service

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=intelbotdb
    username: ${DB_USERNAME:}
    password: ${DB_PASSWORD:}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        default_schema: intelbotdb
    show-sql: true
    defer-datasource-initialization: true

  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql

server:
  port: 8081

jwt:
  secret: ${JWT_SECRET:}
  expiration: ${JWT_EXPIRATION:3600000} # 1 hour in ms
  refresh-expiration: ${JWT_REFRESH_EXPIRATION:604800000} # 7 days in ms

logging:
  level:
    org.springframework.security: INFO

openai:
  api-key: ${OPENAI_API_KEY:}
  base-url: https://api.openai.com/v1
  model: gpt-4.1-mini

perplexity:
  api-key: ${PERPLEXITY_API_KEY:}
  base-url: https://api.perplexity.ai
  model: sonar

rca:
  service-url: ${RCA_SERVICE_URL:http://localhost:8080/api/query/markdown}

data:
  service-url: ${DATA_SERVICE_URL:http://localhost:8083/api/v1/query}


